package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbBusNumber;
import org.apache.ibatis.annotations.Param;

public interface TbBusNumberMapper {

    /**
     * This method was generated by MyBatis Generator.
     */
    TbBusNumber selectByPrimaryKey(@Param("busId") String busId);
}
