package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbBus;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbBusMapper {
    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String busId);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insert(TbBus record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insertSelective(TbBus record);

    /**
     * This method was generated by MyBatis Generator.
     */
    TbBus selectByPrimaryKey(String busId);

    /**
     * 根据busId查询busNumber
     */
    String selectBusNumberIdByBusId(@Param("busId") String busId);


    /**
     * 模糊查询公交车（可根据公交车的名称查询，或者公交车牌号查询）
     */
    List<TbBus> likeBusByName(@Param("pageSize") Integer pageSize, @Param("pageNo") Integer pageNo, @Param("busType") String busType);


    /**
     * 模糊查询公交车（可根据公交车的名称查询，或者公交车牌号查询）
     */
    List<TbBus> likeBusByNameAll();

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKeySelective(TbBus record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKey(TbBus record);
}