package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbDriverRating;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TbDriverRatingMapper {

    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String driverRatingId);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insert(TbDriverRating record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insertSelective(TbDriverRating record);

    /**
     * This method was generated by MyBatis Generator.
     */
    TbDriverRating selectByPrimaryKey(String driverRatingId);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKeySelective(TbDriverRating record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKey(TbDriverRating record);
}