package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbInformation;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String informationId);

    /**
     * 根据文章的唯一标识概念性删除
     */
    int deleteByInformationCode(@Param("informationCode") String informationCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_information
     *
     * @mbggenerated
     */
    int insert(TbInformation record);

    /**
     * 单个添加文章信息
     */
    int insertSelective(TbInformation record);

    /**
     * 根据单个文章的唯一标识code改变文章的信息
     */
    int updateByCode(TbInformation record);

    /**
     * 根据文章的唯一标识获取文章的信息
     */
    TbInformation selectByCode(String informationCode);

    /**
     * 根据二级分类的唯一标识code模糊查询（可分页）
     */
    List<TbInformation> appFindPage(@Param("name") String name, @Param("twoClassifyCode") String twoClassifyCode);


    /**
     * 根据一级级分类的唯一标识code模糊查询（可分页）
     */
    List<TbInformation> findClassifyCode(@Param("name") String name, @Param("classifCode") String classifCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_information
     *
     * @mbggenerated
     */
    TbInformation selectByPrimaryKey(String informationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TbInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbInformation record);
}