package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbListenOrder;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbListenOrderMapper {


    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insert(TbListenOrder record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insertSelective(TbListenOrder record);

    /**
     * This method was generated by MyBatis Generator.
     */
    TbListenOrder selectByPrimaryKey(String id);

    /**
     * 根据乘客订单的唯一标识查询监听订单
     */
    TbListenOrder selByPassengerOrderCode(@Param("passengerOrderCode") String passengerOrderCode);

    /**
     * 根据司机订单的唯一标识查询监听订单
     */
    TbListenOrder selByDriverOrderCode(@Param("driverOrderCode") String driverOrderCode);

    /**
     * 查询所有乘客发起的完成订单请求状态为0的
     */
    List<TbListenOrder> listenAllOrder();

    /**
     * 根据乘客订单的唯一标识修改监听订单的状态
     */
    int updateByByPassengerOrderCode(@Param("passengerOrderCode") String passengerOrderCode, @Param("state") String state);

    /**
     * 根据司机订单的唯一标识修改监听订单的状态
     */
    int updateByDriverOrderCode(@Param("driverOrderCode") String driverOrderCode, @Param("state") String state);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKeySelective(TbListenOrder record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKey(TbListenOrder record);
}