package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbOneClassify;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbOneClassifyMapper {

    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String oneClassifyId);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insert(TbOneClassify record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insertSelective(TbOneClassify record);

    /**
     * This method was generated by MyBatis Generator.
     */
    TbOneClassify selectByPrimaryKey(String oneClassifyId);

    /**
     * 根据一级栏目的code查找
     */
    TbOneClassify selectByOneClassifCode(@Param("oneClassifCode") String oneClassifCode);

    /**
     * 查询所有的一级栏目
     */
    List<TbOneClassify> selAllClassify();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_one_classify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbOneClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_one_classify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbOneClassify record);
}