package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbParm;

import java.util.List;

public interface TbParmMapper {

    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String parmId);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insert(TbParm record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insertSelective(TbParm record);

    /**
     * This method was generated by MyBatis Generator.
     */
    TbParm selectByPrimaryKey(String parmId);

    /**
     * 根据类别参数类型查找参数列表
     */
    List<TbParm> selParmByType(String numberType);

    /**
     * 根据类别参数id数组查询
     */
    List<TbParm> selectByIds(String[] parmIds);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKeySelective(TbParm record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKey(TbParm record);
}