package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbRegularBus;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbRegularBusMapper {

    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String regularBusId);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insert(TbRegularBus record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insertSelective(TbRegularBus record);

    /**
     * This method was generated by MyBatis Generator.
     */
    TbRegularBus selectByPrimaryKey(String regularBusId);

    /**
     * 根据路线的唯一标识查询绑定的车辆.
     */
    List<String> selectByBusRoute(@Param("busRoute") String busRoute);

    /**
     *
     */
    int updateByPrimaryKeySelective(TbRegularBus record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKey(TbRegularBus record);
}