package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbRouteDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbRouteDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insert(TbRouteDetail record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insertSelective(TbRouteDetail record);

    /**
     * This method was generated by MyBatis Generator.
     */
    TbRouteDetail selectByPrimaryKey(String id);

    /**
     * 求距离最近的一个点
     */
    TbRouteDetail selectByDistance(@Param("routeCode") String routeCode, @Param("la") String la, @Param("lo") String lo);

    /**
     * 根据路线的唯一标识查询要绘制的路线明细的经纬度
     */
    List<TbRouteDetail> getBusRoutelDetails(@Param("routeCode") String routeCode);

    /**
     * 查询这两点之间所有的经纬度点，根据序号排序（升序）
     */
    List<TbRouteDetail> selectBySort(@Param("routeCode") String routeCode, @Param("sort1") Integer sort1, @Param("sort2") Integer sort2);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKeySelective(TbRouteDetail record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKey(TbRouteDetail record);

}