package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbSite;
import org.apache.ibatis.annotations.Param;

public interface TbSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String siteId);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insert(TbSite record);

    /**
     *
     */
    int insertSelective(TbSite record);

    /**
     * This method was generated by MyBatis Generator.
     */
    TbSite selectByPrimaryKey(String siteId);


    /**
     * 根据多个站点查询站点信息
     */
    TbSite selectBySiteCodes(@Param("siteCode") String siteCode);

    /**
     * 根据一个站点查询站点信息
     */
    TbSite selectBySiteCode(@Param("siteCode") String siteCode);

    /**
     * 查询离当前最近的站点
     */
    TbSite getSiteByLoLa(@Param("NowLa") String NowLa, @Param("NowLo") String NowLo, @Param("siteCodes") String[] siteCodes);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKeySelective(TbSite record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKey(TbSite record);
}