package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbSysRole;

import java.util.List;

public interface TbSysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByCode(String code);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insert(TbSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insertSelective(TbSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     */
    TbSysRole selectByPrimaryKey(String id);

    /**
     * 根据角色的code查找角色信息
     */
    TbSysRole selectByCode(String code);

    /**
     * This method was generated by MyBatis Generator.
     */
    List<TbSysRole> selSysRole(String name);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKeySelective(TbSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKey(TbSysRole record);
}