package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbSysPermissions;

import java.util.List;

public interface TbSysPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByCode(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_permissions
     *
     * @mbggenerated
     */
    int insert(TbSysPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_permissions
     *
     * @mbggenerated
     */
    int insertSelective(TbSysPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_permissions
     *
     * @mbggenerated
     */
    TbSysPermissions selectByPrimaryKey(String id);

    /**
     * 根据权限code查找
     */
    TbSysPermissions selectByCode(String code);


    /**
     * 根据多个权限的code查找权限
     */
    List<TbSysPermissions> selectByCodes(String[] codes);


    /**
     * This method was generated by MyBatis Generator.
     */
    List<TbSysPermissions> selSysPermissions(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbSysPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbSysPermissions record);
}