package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbSysModule;

import java.util.List;

public interface TbSysModuleMapper {


    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByCode(String code);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insert(TbSysModule record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int insertSelective(TbSysModule record);

    /**
     * This method was generated by MyBatis Generator.
     */
    TbSysModule selectByPrimaryKey(String id);

    /**
     * 根据多个模块code查找所有模块
     */
    List<TbSysModule> selByModuleCodes(String[] codes);

    /**
     * This method was generated by MyBatis Generator.
     */
    List<TbSysModule> selSysModule(String name);

    /**
     * This method was generated by MyBatis Generator.
     */
    TbSysModule selectByCode(String code);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKeySelective(TbSysModule record);

    /**
     * This method was generated by MyBatis Generator.
     */
    int updateByPrimaryKey(TbSysModule record);
}