package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbTravel;

public interface TbTravelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_travel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String travelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_travel
     *
     * @mbggenerated
     */
    int insert(TbTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_travel
     *
     * @mbggenerated
     */
    int insertSelective(TbTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_travel
     *
     * @mbggenerated
     */
    TbTravel selectByPrimaryKey(String travelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_travel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbTravel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_travel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbTravel record);
}