package com.tangmo.zhygzhglxt.dao;

import com.tangmo.zhygzhglxt.entity.TbTwoClassify;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbTwoClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_two_classify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_two_classify
     *
     * @mbggenerated
     */
    int insert(TbTwoClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_two_classify
     *
     * @mbggenerated
     */
    int insertSelective(TbTwoClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_two_classify
     *
     * @mbggenerated
     */
    TbTwoClassify selectByPrimaryKey(String id);

    /**
     * 根据二级栏目的唯一标识查找
     */
    TbTwoClassify selectByTwoClassifCode(@Param("twoClassifCode") String twoClassifCode);

    /**
     * This method was generated by MyBatis Generator.
     */
    List<TbTwoClassify> getTwoClassifyCode(@Param("classifCode") String classifCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_two_classify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbTwoClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_two_classify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbTwoClassify record);
}